In [2]:
# 1- Importing datasets and important library required
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
import pandas as pd

In [3]:
# 2- Fetching data from the sklearn's built-in dataset
data = fetch_california_housing ()
df = pd.DataFrame(
    data.data,
    columns=data.feature_names
)
df["target"] = data.target
print(df.head().to_string())

   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  Longitude  target
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88    -122.23   4.526
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86    -122.22   3.585
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85    -122.24   3.521
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85    -122.25   3.413
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85    -122.25   3.422


In [4]:
# 3- Printing first 10 rows
print(df.head(10))

   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
5  4.0368      52.0  4.761658   1.103627       413.0  2.139896     37.85   
6  3.6591      52.0  4.931907   0.951362      1094.0  2.128405     37.84   
7  3.1200      52.0  4.797527   1.061824      1157.0  1.788253     37.84   
8  2.0804      42.0  4.294118   1.117647      1206.0  2.026891     37.84   
9  3.6912      52.0  4.970588   0.990196      1551.0  2.172269     37.84   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422  
5    -122.25   2.697  
6 

In [5]:
# 4- Overall info
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
 8   target      20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB
None


In [6]:
# 5- Splitting feature and target
x = data.data
y = data.target
print("Features--->")
print(x)
print("Target--->")
print(y)

Features--->
[[   8.3252       41.            6.98412698 ...    2.55555556
    37.88       -122.23      ]
 [   8.3014       21.            6.23813708 ...    2.10984183
    37.86       -122.22      ]
 [   7.2574       52.            8.28813559 ...    2.80225989
    37.85       -122.24      ]
 ...
 [   1.7          17.            5.20554273 ...    2.3256351
    39.43       -121.22      ]
 [   1.8672       18.            5.32951289 ...    2.12320917
    39.43       -121.32      ]
 [   2.3886       16.            5.25471698 ...    2.61698113
    39.37       -121.24      ]]
Target--->
[4.526 3.585 3.521 ... 0.923 0.847 0.894]


In [7]:
# 6- Checking for null values
print(df.isnull().sum())

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
target        0
dtype: int64


In [8]:
# 7- Splitting training and testing  (70%---> Training  30%---> Testing)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
        x,
        y,
        test_size = 0.3,
        random_state = 42
)

In [9]:
# 8- Encoding
print(df.dtypes)


# Since every data is numeircal no need to do encoding

MedInc        float64
HouseAge      float64
AveRooms      float64
AveBedrms     float64
Population    float64
AveOccup      float64
Latitude      float64
Longitude     float64
target        float64
dtype: object


In [10]:
# 9- Scaling data
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
scale.fit_transform(X_train)
scale.fit(X_test)

StandardScaler()

In [11]:
# 10- Model creation
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](8,)","[ 0.45, 0.01,-0.12,...,-0. ,-0.42,-0.43]"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,-37.06
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,8
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int,8
"singular_ singular_: array of shape (min(X, y),)Singular values of `X`. Only available when `X` is dense.","ndarray[float64](8,)","[137050.9 , 1501.07, 1433.16,..., 207.71, 60.45, 19.95]"


In [12]:
# 11- Making prediction
y_pred = model.predict(X_test)
print(y_pred[:5])

[0.72604907 1.76743383 2.71092161 2.83514727 2.60695807]


In [13]:
# 12- Converting the 1D predited data to 2D for table like comparison
y_pred_2d = y_pred.reshape(len(y_pred),1)
y_pred_2d


array([[0.72604907],
       [1.76743383],
       [2.71092161],
       ...,
       [2.07465531],
       [1.57371395],
       [1.82744133]], shape=(6192, 1))

In [14]:
# 13- Converting the 1D y_test data to 2D for table like comparison
y_test_2d = y_test.reshape(len(y_test),1)
y_test_2d

array([[0.477  ],
       [0.458  ],
       [5.00001],
       ...,
       [2.184  ],
       [1.194  ],
       [2.098  ]], shape=(6192, 1))

In [15]:
# 14- Creating dataframes of both 2D data with a defined heading
df1 = pd.DataFrame(y_pred_2d,columns=["Predicted"])
df2 = pd.DataFrame(y_test_2d, columns=['Real'])

In [16]:
# 15- Concatinating both dataframes for getting a table-like comparison
pd.concat([df1,df2],axis=1)

,Predicted,Real
0,0.726049,0.47700
1,1.767434,0.45800
2,2.710922,5.00001
3,2.835147,2.18600
4,2.606958,2.78000
...,...,...
6187,2.219941,2.37500
6188,0.910516,0.67300
6189,2.074655,2.18400
6190,1.573714,1.19400


In [17]:
# 16- Concatinating both dataframes for getting a table-like comparison
comparison = pd.concat([df1,df2],axis=1)
print(comparison)

      Predicted     Real
0      0.726049  0.47700
1      1.767434  0.45800
2      2.710922  5.00001
3      2.835147  2.18600
4      2.606958  2.78000
...         ...      ...
6187   2.219941  2.37500
6188   0.910516  0.67300
6189   2.074655  2.18400
6190   1.573714  1.19400
6191   1.827441  2.09800

[6192 rows x 2 columns]


In [18]:
# 17- Final statistics output
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
print("MAE:", mean_absolute_error(y_test, y_pred))

print("MSE:", mean_squared_error(y_test, y_pred))

print("RMSE:", mean_squared_error(y_test, y_pred) ** 0.5)

print("R2 Score:", r2_score(y_test, y_pred))

MAE: 0.5272474538306168
MSE: 0.5305677824766757
RMSE: 0.7284008391515455
R2 Score: 0.595770232606166


In [20]:
# 18- Final output
print(comparison.head(20))

    Predicted     Real
0    0.726049  0.47700
1    1.767434  0.45800
2    2.710922  5.00001
3    2.835147  2.18600
4    2.606958  2.78000
5    2.010739  1.58700
6    2.640674  1.98200
7    2.167062  1.57500
8    2.740121  3.40000
9    3.903615  4.46600
10   0.944419  1.23200
11   1.901237  2.53900
12   1.763534  2.15100
13   2.252804  2.20500
14   2.537990  2.19800
15   1.922175  1.36200
16   2.387974  1.78400
17   2.012288  1.87500
18   2.224112  1.39800
19   1.126040  1.37500
